version: "3"

services:
  app:
    build: ../docker/
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ../db:/db
    environment:
      - DB_PATH=/db/MIAUTOMEC.FDB
      - DB_USER=SYSDBA
      - DB_PASSWORD=a13677628bd629e12f5e
  db:
    image: jacobalberty/firebird:2.5-ss
    ports:
      - 3050:3050
    volumes:
      - ./db:/databases